### ISSUE TITLE
Fair use of your project

### ISSUE THREAD

**Issue by emiln** [kwhat/jnativehook#68] opened 2015-09-22 15:45 UTC
Hello, kwhat.

Your library is exactly what I need for a project I'm undertaking. I will be using a `java.awt.Robot` to automate a lot of mouse and keyboard actions, and I need a reliable way to kill the Robot with a global keybinding. Your library is the only I've stumbled upon that offers this in a fully Java-integrated fashion, so thumbs up for your outstanding work.

The license notice printed to system out interferes somewhat with the kind of CLI I had in mind, however, so my question is this:

Do you mind me hiding this license message, given that my project will be clearly marked as under a GPLv3 license through its Github page and source code?

**Comment by kwhat** [comment] 2015-09-22 16:23
Hi Emiln, 

It has been removed in the 2.0 branch, and will be released with 2.0.3.  I am trying to get a few bug fixes in, but I have been short on time this month.  Hopefully I can get some work done this weekend and release soon.  This ticket is a duplicate of two others, but I will leave it open until 2.0.3 is released.  On a side note, this library does offer robot functionality if you need it.

-Alex

**Comment by emiln** [comment] 2015-09-23 09:10
Thank you for your quick response. That's great news–I will just leave the license printing as is for now and update to version 2.0.3 when it is released.

**Closed** 2015-10-16 06:43 UTC
Labels: duplicate
