### ISSUE TITLE
does jnativehook support various displays on linux?

### ISSUE THREAD

**Issue by himourfasy** [kwhat/jnativehook#69] opened 2015-09-25 11:11 UTC
Hi
we found former instance crash when a second start on the same machine. is this a bug or valid behavior?
and then we enhanced to prevent multiple instances on one single display.
but with multiple displays started, the vm still crash, when:
 a. start jnativehook on display :1 
 b. start on display :0
 c. then the vm on :1 crashes.
any suggestions? if the crash log is needed, I will paste it here then. thanks.

**Comment by kwhat** [comment] 2015-09-25 14:06
No effort has been made to support anything beyond the default display.  Please attach the crash log if you have it.  I'll take a look tomorrow.

**Comment by kwhat** [comment] 2015-09-25 14:54
It looks like its crashing the jvm from the hook thread for me when starting on the same display.

**Comment by himourfasy** [comment] 2015-09-27 06:31
thanks for your quick reply. yes, then with different displays it crashed in the same thread, maybe at the same place.

>Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
>j  org.jnativehook.GlobalScreen$NativeHookThread.enable()V+0
>j  org.jnativehook.GlobalScreen$NativeHookThread.run()V+6
>v  ~StubRoutines::call_stub

if you need I should create a simple test case to clear off the service logic in error log content.

**Comment by kwhat** [comment] 2015-10-15 15:29
So I tried to debug outside of Java and the problem does not occur.  The segfault seems to happen at where ever the hook_event_proc is currently executing.  I'm not sure what the problem is but it doesn't seem like its directly related to the native library.  

(gdb) bt full
#0  0x0000000000002386 in ?? ()
No symbol table info available.
#1  0x00007f80be870ac0 in hook_event_proc (closeure=0x0, recorded_data=0x7f805c016e50) at /home/kwhat/IdeaProjects/JNativeHook/src/libuiohook/src/x11/input_hook.c:207
        timestamp = 0
        __func__ = "hook_event_proc"
#2  0x0000003c7e801af6 in ?? () from /usr/lib64/libXtst.so.6
No symbol table info available.
#3  0x0000003c7e802bb0 in XRecordEnableContext () from /usr/lib64/libXtst.so.6
No symbol table info available.
#4  0x00007f80be871c65 in hook_run () at /home/kwhat/IdeaProjects/JNativeHook/src/libuiohook/src/x11/input_hook.c:792
        closeure = 0x0
        clients = 3
        is_auto_repeat = 1
        major = 1
        minor = 13
        status = 1
        __func__ = "hook_run"
#5  0x00007f80be86fbd8 in Java_org_jnativehook_GlobalScreen_00024NativeHookThread_enable (env=0x7f805812e1e8, Thread_obj=0x7f80bdc776e0) at /home/kwhat/IdeaProjects/JNativeHook/src/jni/org_jnativehook_GlobalScreen.c:34
        status = 32640
#6  0x00007f80c855e7f8 in ?? ()
No symbol table info available.
#7  0x00007f805812e000 in ?? ()
No symbol table info available.
#8  0x0000000000000130 in ?? ()
No symbol table info available.
#9  0x00007f80bdc77680 in ?? ()
No symbol table info available.
#10 0x0000000682cb79c0 in ?? ()
No symbol table info available.
#11 0x00007f80bdc776e0 in ?? ()
No symbol table info available.
#12 0x0000000682cb7e88 in ?? ()
No symbol table info available.
#13 0x0000000000000000 in ?? ()
No symbol table info available.

**Comment by kwhat** [comment] 2015-10-16 05:43
So I figured what was going on.  Basically the jar extracts the native library to disk and loads it if you didn't define java.library.path when starting the JVM.  The fun part comes when Linux overwrites the shared object while its in use.

**Comment by kwhat** [comment] 2015-10-16 06:39
fix is in the 2.0 branch.

**Closed by kwhat** 2015-10-16 06:39 UTC
Labels: bug
