### ISSUE TITLE
Accented characters do not work 

### ISSUE THREAD

**Issue by edsonqr** [kwhat/jnativehook#288] opened 2020-04-11 01:36 UTC
While the jnativehook is running, accented characters and quotation marks before words do not work. Example: ú ã "test"

**Comment by dtsw** [comment] 2020-05-22 09:42
i can confirm, as soon as i do GlobalScreen.registerNativeHook(), the ¨ or ` etc. keys are "ignored".

**Comment by blueglyph** [comment] 2020-09-13 10:17
Works for me, maybe you want to give a little more information, it is very vague.

**Comment by kwhat** [comment] 2021-09-27 21:33
There was a fix for this in 2.2.0 that was just released.  If this is still and issue, please reopen and be sure to specify your OS and version.

**Closed as completed by kwhat** 2021-09-27 21:33 UTC
Labels: bug, duplicate
