### ISSUE TITLE
nativeMousePressed -> different getButton() result on Win/Linux

### ISSUE THREAD

**Issue by benjaminaigner** [kwhat/jnativehook#196] opened 2017-10-03 13:58 UTC
Running a demo code with following Button mapping results in different output on Windows/Linux machines:

```
	public void nativeMouseClicked(NativeMouseEvent e) {
		System.out.println("Mouse Clicked: " + e.getClickCount());
		switch(e.getButton())
		{
		case NativeMouseEvent.BUTTON1:
			System.out.println("Button 1 (Left?) pressed");
			break;
		case NativeMouseEvent.BUTTON2:
			System.out.println("Button 2 (Middle?) pressed");
			break;
		case NativeMouseEvent.BUTTON3:
			System.out.println("Button 3 (Right?) pressed");
			break;
		}
	}
```

On Linux (Debian stretch/sid) output is according to console output:
BUTTON1 -> left click
BUTTON2 -> middle click
BUTTON3 -> right click

if I run the same code on Win7,
BUTTON1 -> left click
BUTTON2 -> right click
BUTTON3 -> middle click

Should I consider this as a bug OR should I build a platform-dependent workaround?

**Comment by kwhat** [comment] 2017-10-04 17:22
I know what the problem is and how to fix it but it never came up before.  Its not really a bug but more of which map to use.  IIRC XKB provides a way to do this lookup but I never implemented it.  I have no idea when I can get to this bug, maybe I will have time if I wake up sometime in the middle of the night next week.

**Comment by benjaminaigner** [comment] 2017-10-05 07:31
No hurry, I'm currently working with an OS dependent assignment.
I'll watch this issue & update the lib+my source if it is fixed.

Thanks!

**Comment by kwhat** [comment] 2022-03-11 06:37
This has been resolved in the [latest snapshot](https://github.com/kwhat/jnativehook/actions/runs/1967211753).

**Closed by kwhat** 2022-03-11 06:37 UTC
Labels: bug, enhancement
