### ISSUE TITLE
Latin accents being intercepted

### ISSUE THREAD

**Issue by leandrocm86** [kwhat/jnativehook#197] opened 2017-10-04 19:45 UTC
Hello! Firstly I'd like to thank you for this API that is helping me on a personal virtual keyboard project I'm doing with Swing.
The only interception I need on this project is mouse clicks outside the application, and that is working just fine. I don't use any keyboard listener. However, I noticed that my system is not registering some keyboard accents when the hook is activated (~, ^, ´ and `). When I press any of those characters they are simply ignored by Windows. I will paste the code I'm using and will be glad to help with any further info you might need. Thank you!
System: Java 1.8.0_102; Windows 10 x64

```java
public class CompleteListener implements (...) NativeMouseInputListener {
    public CompleteListener(...)  {  // Constructor
        (...)
	Logger logger = Logger.getLogger(GlobalScreen.class.getPackage().getName());
	logger.setLevel(Level.OFF);
	logger.setUseParentHandlers(false);
	GlobalScreen.registerNativeHook();
	GlobalScreen.addNativeMouseListener(this);
    }

    @Override
    public void nativeMouseClicked(NativeMouseEvent arg0) {     // Only method I actually use 
        if (arg0.getX() < mainFrame.getLocation().x || arg0.getX() > mainFrame.getLocation().x + Main.FRAME_WIDTH) {
            this.textoDigitado.limpar();
            resetLabels();
        }
        else if (arg0.getY() < mainFrame.getLocation().y || arg0.getY() > mainFrame.getLocation().y + Main.FRAME_HEIGHT) {
            this.textoDigitado.limpar();
            resetLabels();
        }
    }

    //Empty implementations (not being used).
    @Override
    public void nativeMousePressed(NativeMouseEvent arg0) {
    }
    @Override
    public void nativeMouseReleased(NativeMouseEvent arg0) {
    }
    @Override
    public void nativeMouseDragged(NativeMouseEvent arg0) {
    }
    @Override
    public void nativeMouseMoved(NativeMouseEvent arg0) {
    }
}

**Comment by kwhat** [comment] 2017-10-04 22:30
This maybe a duplicate of a memory corruption issue that I have yet to duplicate with non-english languages on Windows.  See issues #183 and #184 for more info.

**Closed** 2017-10-10 12:28 UTC
